---
title: "try creating crossbasis matrix to model"
author: "Meilin Yan"
date: "September 22, 2016"
output: html_document
---

```{r include=FALSE}
library(lubridate)
library(dplyr)
library(dlnm)
library(splines)

readCity <- function(city = c(), collapseAge = TRUE){
  root <- "~/tmp/NMMAPS/"
  file <- paste(root, city, ".rds", sep = "")
  df <- readRDS(file)

  if(collapseAge == TRUE){
    df <- rowsum(df[,c("alldeath", "death", "accident", "cvd", "resp",
                       "copd", "suicide", "tmpd", "dptp")], df$date,
                 reorder = FALSE)
    df$date <- as.Date(rownames(df))
    df[ , c("tmpd", "dptp")] <- df[ , c("tmpd", "dptp")]/3
    df$dow <- as.factor(as.POSIXlt(df$date)$wday)
  }
  
  return(df)
}

readStorm <- function(criterion = c(), city = c()){
  root <- "exposure/"
  file <- paste(root, criterion, "/", city, ".rds", sep = "")
  df <- readRDS(file)
  df <- as.data.frame(df)
  df$date <- lubridate::ymd(df$closest_date)
  
  return(df)
}

city.storm <- function(criterion = c(), city = c()){
  # Get health data
  h.df <- readCity(city)
  # Get storm data
  s.df <- readStorm(criterion, city)
  
  storm_days <- s.df$date
  
  df <- left_join(h.df, s.df, by = "date") %>%
        mutate(hurr = ifelse(date %in% storm_days, 1, 0))
  df$hurr <- as.factor(df$hurr)
  
  # Add abbreviate and full cityname
  df$city <- city
  sub.county <- readRDS("data/sub.county.rds")
     
  cityname <- sub.county$citynameU[sub.county$city == city]
  df$cityname <- cityname
  
  #df$time <- scale(as.numeric(df$date), center = TRUE, scale = FALSE)
  #n.years <- length(unique(as.POSIXlt(df$date)$year))
  df$year <- year(df$date)
  df$doy <- yday(df$date)
  
  # Total death
  df$all <- df$accident + df$death
  
  return(df)
}
```

#### Try creating crossbasis matrix by using data of Miami (criterion: 75mm rainfall)
```{r}
df <- city.storm(criterion = "rain75", city = "miam")

df$time <- 1:length(df$hurr)
cand_control <- unique(c(which(df$hurr == 1) , which(df$hurr == 1) + 1,
                         which(df$hurr == 1) - 1))
df$cand_control <- TRUE
df$cand_control[cand_control] <- FALSE

case_dates <- subset(df, hurr == 1) # hurr is exposure
control_dates <- subset(df, hurr == 0)
control.ratio <- 15
for(i in 1:nrow(case_dates)){
  control_range <- case_dates$doy[i] + -3:3 
  control_subset <- subset(control_dates, 
                           control_dates$year != case_dates$year[i] &
                           doy %in% control_range & 
                           cand_control) 
  controls <- sample_n(control_subset, control.ratio)
  stratum <- paste("stratum", i, sep = ".")
  i_stratum <- rbind(case_dates[i, ], controls)
  i_stratum$stratum <- stratum
  
  if(i == 1){
    new_df <- i_stratum
  } else {
    new_df <- rbind(new_df, i_stratum)
  }
}

# merge with df
new_df <- select(new_df, date, stratum)
df <- left_join(df, new_df, by = "date")
df$stratum <- as.factor(df$stratum)

# original crossbasis
cb <- crossbasis(df$hurr, lag = c(0, 13), 
                 argvar = list(fun = "lin"),
                 arglag = list(fun = "ns", knots = c(1, 4, 8)))

# create crossbasis matrix to model
strata <- levels(df$stratum)
by_row <- rownames(subset(df, stratum %in% strata))
by_row <- as.numeric(by_row)

cb <- as.data.frame(cb)
cb_to_mod <- as.matrix(cb[by_row, ])

# get data to model
df_to_mod <- subset(df, stratum %in% strata)

# this data of Miami has 8 storms, we choose 15 controls(days) for each storm. So both the crossbasis and data included in the model have 16*8 = 128 rows.
model <- glm(all ~ cb_to_mod + ns(year, 2) + stratum, 
             eliminate = stratum,
             family = quasipoisson(link = log),
             data = df_to_mod,
             control = glm.control(epsilon = 10E-8, maxit = 5000))

summary(model)
```

[MY: There is a tricky thing. The total df for the crossbasis is 5 (with 3 interior knots for lag and linear function for variable). So we are supposed to have 5 coefficients for crossbasis in the summary of model. However, each time when I knit this file, I might have 1, 2, 3, or 4 coefficients for crossbasis. I beileve it is because we choose the "controls" for each storm by randomly sampling. 
\
I still can not get 5 coefficients. Once there is a NA coefficient, the crosspred just can not work.]